[WIP]#160583965 Users should be able to comment on articles
andela/ah-frontend-stark pull request #13
Opened 2018-11-08 17:39 UTC by j0flintking02

### What does this PR do?
Users should be able to comment on articles
### Description of the 
Comments allow authors to get feedback on their articles.. We all love to know what people think about what we put out to the world
### Relevant PT stories?
[#160583965](https://www.pivotaltracker.com/n/projects/2198584/stories/160583965)

2018-11-15 04:01 UTC, balaakagordon approved these changes
LGTM

2018-11-15 11:53 UTC, lym requested changes

2018-11-15 11:53 UTC, lym commented on .gitignore
> +.idea/*
Add a new line here

2018-11-15 11:53 UTC, lym commented on src/App.js
> -
Remove this new blank line. Let's have only two empty lines between import and class declaration.

2018-11-15 11:53 UTC, lym commented on src/actions/commentAction.js
> +};
Add a blank line here

2018-11-15 11:53 UTC, lym commented on src/tests/commentReducer.test.js
> +  });
Have at least a blank line separating the examples, for easy readability.

2018-11-15 11:53 UTC, lym commented on src/tests/comments.test.js
> +});
Add a line here for easy readability.

2018-11-15 13:33 UTC, kenneth051 requested changes
Good job Jonathan, Could you please make the PR more descriptive. I don't know what URL link to go to when testing the feature. Thank you

2018-11-16 12:27 UTC, kenneth051 approved these changes

2018-11-22 20:55 UTC, merged