feat():Users should be able to update and delete articles
andela/ah-frontend-stark pull request #20
Opened 2018-11-16 09:51 UTC by kenneth051

**What does this PR do?**
Enables users to delete and edit articles.

**Description of task to be completed**
Articles form the backbone of our application. This task enables users to delete and edit the contents of an article. Only authenticated users can delete and edit articles.

**How should this be manually tested?**
Clone the repository, checkout into this branch
- Run `yarn install` to install all dependencies
- Run  `yarn test` to run the tests
- Run `yarn start`
register or login
- go to the create article endpoint  ```http://localhost:3000/createArticle/```
- Go to my articles endpoint, ```http://localhost:3000/myArticles``` click on edit or delete

**Relevant Pivotal Tracker Stories**

[#160583963](https://www.pivotaltracker.com/n/projects/2198584/stories/160583963)

#### Any background context you want to add?
N/A

**Screen shots**

<img width="1233" alt="screen shot 2018-11-16 at 12 48 05" src="https://user-images.githubusercontent.com/40117122/48613918-0d2da580-e99e-11e8-8784-bb4b0c11e9c0.png">

<img width="1212" alt="screen shot 2018-11-16 at 12 48 18" src="https://user-images.githubusercontent.com/40117122/48613980-2fbfbe80-e99e-11e8-8cea-4f3ebc2532fd.png">

2018-11-16 10:18 UTC, balaakagordon approved these changes
LGTM

2018-11-19 06:51 UTC, Edward-K1 commented
Good work @kenneth051 but please update the 'my articles' option on the navigation bar dropdown to point to a user's articles.

2018-11-19 08:09 UTC, Edward-K1 commented on src/index.css
> +.card {
Please don't override the default bootstrap card class. This will make other features dependent on it display incorrectly.

2018-11-19 10:18 UTC, Edward-K1 commented
LGTM.

2018-11-19 12:10 UTC, nakimera requested changes
Would you change the colour of the article title on the article cards to blue and display the author's profile picture on the article cards.

2018-11-20 12:21 UTC, j0flintking02 approved these changes
LGTM

2018-11-20 13:13 UTC, Edward-K1 approved these changes
LGTM.

2018-11-20 16:45 UTC, nakimera approved these changes

2018-11-20 16:51 UTC, merged