#160583955 set up react router
andela/ah-frontend-stark pull request #4
Opened 2018-10-31 05:24 UTC by balaakagordon

#### What does this PR do?
Set up routing for navigation between pages
#### Description of Task to be completed?
- enable navigation, in the browser, to the following endpoints:
`'/'`
`'/login'`
- display error message for other endpoints
#### How should this be manually tested?
After pulling the branch:
- update dependencies using
`npm install`
- run the application using
`npm start`
- navigate to the aforementioned endpoints
- try visiting an endpoint that does not exist yet
#### What are the relevant pivotal tracker stories?
#160583955 - Setup react router version 4 (React-router-dom)
https://www.pivotaltracker.com/n/projects/2198584/stories/160583955
#### Screenshots (if appropriate)
Landing page
![image](https://user-images.githubusercontent.com/40589388/47767785-47cce800-dce6-11e8-9f0c-af72071ed6c7.png)
-------------------------------------------------------------------------------------------------

Login page
![image](https://user-images.githubusercontent.com/40589388/47767773-371c7200-dce6-11e8-817e-5b003c4887c9.png)
-------------------------------------------------------------------------------------------------

Page doesn't exist
![image](https://user-images.githubusercontent.com/40589388/47767813-603d0280-dce6-11e8-8b40-6c8fb5ae70c3.png)
-------------------------------------------------------------------------------------------------

2018-10-31 06:45 UTC, kenneth051 requested changes
Nice work Gordon the routes do work. However, when I add a slash and some words on the login route, it still navigates to the login page. Try adding "exact" to all the routes and we see if it will catch the route errors. I also haven't seen any tests written for the feature.

2018-10-31 06:51 UTC, balaakagordon commented
Thanks for the feedback, Kenneth. I have implemented the changes

2018-10-31 11:59 UTC, kenneth051 approved these changes

2018-11-01 13:09 UTC, kenneth051 commented on .eslintrc.json
> +<<<<<<< HEAD
@balaakagordon, please resolve these conflicts.

2018-11-01 13:11 UTC, kenneth051 commented on src/App.js
> +const App = () => (
@balaakagordon Since we will have to use state, could you please revert this back to a class-based component.

2018-11-01 16:33 UTC, kenneth051 commented
LGTM

2018-11-01 16:33 UTC, j0flintking02 approved these changes
LGTM

2018-11-01 16:34 UTC, merged